---
title: "Evaluating Ranking Methodologies for UFC Fighters"
author: "Michael Goldschlager"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(elo)
library(PlayerRatings)
library(foreach)
library(doSNOW)
library(parallel)
```

## Load Data

```{r}
ufc_data <- read.csv("data.csv")[, c("R_fighter", "B_fighter", "date", "Winner")]
```

## Data Prep

```{r}
ufc_data$R_win <- 0
ufc_data$R_win[which(ufc_data$Winner == "Red")] <- 1
ufc_data$R_win[which(ufc_data$Winner == "Draw")] <- .5

ufc_data$B_win <- 0
ufc_data$B_win[which(ufc_data$Winner == "Blue")] <- 1
ufc_data$B_win[which(ufc_data$Winner == "Draw")] <- .5

ufc_data$date <- as.Date(ufc_data$date)
ufc_data$date_numeric <- as.numeric(ufc_data$date)

ufc_data <- ufc_data[order(ufc_data$date), ]

ufc_data$R_elo_before <- NA
ufc_data$B_elo_before <- NA

ufc_data$R_elo_after <- NA
ufc_data$B_elo_after <- NA
```

## Elo

```{r}
#Elo generation
fighters <- unique(c(ufc_data$R_fighter, ufc_data$B_fighter))
fighter_elo <- data.frame(fighter = fighters, elo = 1500)

k_list <- seq(170, 250, 5)

cluster <- makeCluster(detectCores() -1)
registerDoSNOW(cluster)

iterations <- length(k_list)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

elo_performance_df <- foreach(i =  1:length(k_list), .combine = 'rbind', .packages = 'elo', .export = c("ufc_data", "fighter_elo"), .options.snow = opts) %dopar% {
  fighter_elo_loop <- fighter_elo
  ufc_data_loop <- ufc_data
  for(j in 1:nrow(ufc_data_loop)) {
    elo_before_r <- fighter_elo_loop[which(fighter_elo_loop$fighter == ufc_data_loop[j,]$R_fighter),]$elo
    elo_before_b <- fighter_elo_loop[which(fighter_elo_loop$fighter == ufc_data_loop[j,]$B_fighter),]$elo
    
    ufc_data_loop[j,]$R_elo_before <- elo_before_r
    ufc_data_loop[j,]$B_elo_before <- elo_before_b
    
    new_elo <- elo.calc(
      wins.A = ufc_data_loop[j,]$R_win,
      elo.A = elo_before_r,
      elo.B = elo_before_b,
      k = k_list[i]
    )
    
    fighter_elo_loop[which(fighter_elo_loop$fighter == ufc_data_loop[j,]$R_fighter),]$elo <- new_elo[1, 1]
    fighter_elo_loop[which(fighter_elo_loop$fighter == ufc_data_loop[j,]$B_fighter),]$elo <- new_elo[1, 2]
    
    ufc_data_loop[j,]$R_elo_after <- new_elo[1, 1]
    ufc_data_loop[j,]$B_elo_after <- new_elo[1, 2]
  }
  
  # Elo Performance
  ufc_data_loop$elo_predict_winner <- NA
  ufc_data_loop$elo_predict_winner[ufc_data_loop$R_elo_before > ufc_data_loop$B_elo_before] <-  "Red"
  ufc_data_loop$elo_predict_winner[ufc_data_loop$B_elo_before > ufc_data_loop$R_elo_before] <- "Blue"
  ufc_data_loop$elo_predict_winner[ufc_data_loop$R_elo_before == ufc_data_loop$B_elo_before] <- "Draw"
  
  ufc_data_loop$elo_prediction_accurate <- NA
  ufc_data_loop$elo_prediction_accurate[ufc_data_loop$elo_predict_winner == ufc_data_loop$Winner] <- 1
  ufc_data_loop$elo_prediction_accurate[ufc_data_loop$elo_predict_winner != ufc_data_loop$Winner] <- 0
  
  cbind(method = "elo" , k = k_list[i], accuracy = mean(ufc_data_loop$elo_prediction_accurate))
}

close(pb)
stopCluster(cluster)

elo_performance_df <- as.data.frame(elo_performance_df)
```
k = 175, best

## Glicko

```{r}
rd_init_vals <- seq(30, 300, 10)
cval_vals <- seq(0, 30, 1)#c(1/2, 1/200, 1/20, 1/10, 1/5)#seq(0, 10, 1)#seems cval doesn't really matter
glicko_params <- expand.grid(rd = rd_init_vals, cval = cval_vals)

cluster <- makeCluster(detectCores() -1)
registerDoSNOW(cluster)

iterations <- nrow(glicko_params)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

glicko_performance <- foreach(i = 1:nrow(glicko_params), .combine = 'rbind', .packages = 'PlayerRatings', .options.snow = opts) %dopar% {
  
  status_df <- NULL
  glicko_rating <- NULL
  ufc_data_loop <- ufc_data
  ufc_data_loop$R_glicko_pred_win_prob <- NA
  ufc_data_loop$B_glicko_pred_win_prob <- NA
  
  for(j in 1:nrow(ufc_data_loop)){
    #fight
    fight <- ufc_data_loop[j, c("date", "R_fighter", "B_fighter", "R_win")]
    fight$date <- as.numeric(fight$date)
    
    #rating prediction
    if(!is.null(glicko_rating)){
      ufc_data_loop[j, ]$R_glicko_pred_win_prob <- predict(glicko_rating, fight[, -4], tng = 1, trat = c(1500, glicko_params[i, ]$rd))
      ufc_data_loop[j, ]$B_glicko_pred_win_prob <- predict(glicko_rating, fight[, c(1,3,2)], tng = 1, trat = c(1500, 30))
    }
    
    #rating generation
    gl <- glicko(fight, status = status_df, init = c(1500, glicko_params[i, ]$rd), cval = glicko_params[i, ]$cval)
    
    #glicko_rating for future predictions
    glicko_rating <- gl
    
    #status for future input
    status_df <- gl$ratings
  }
  
  #Glicko Performance
  ufc_data_loop$glicko_predict_winner <- NA
  ufc_data_loop$glicko_predict_winner[ufc_data_loop$R_glicko_pred_win_prob > ufc_data_loop$B_glicko_pred_win_prob] <-  "Red"
  ufc_data_loop$glicko_predict_winner[ufc_data_loop$R_glicko_pred_win_prob < ufc_data_loop$B_glicko_pred_win_prob] <- "Blue"
  ufc_data_loop$glicko_predict_winner[ufc_data_loop$R_glicko_pred_win_prob == ufc_data_loop$B_glicko_pred_win_prob] <- "Draw"

  ufc_data_loop$glicko_prediction_accurate <- NA
  ufc_data_loop$glicko_prediction_accurate[ufc_data_loop$glicko_predict_winner == ufc_data_loop$Winner] <- 1
  ufc_data_loop$glicko_prediction_accurate[ufc_data_loop$glicko_predict_winner != ufc_data_loop$Winner] <- 0

  cbind(method = "glicko" ,
        rd = glicko_params[i, ]$rd,
        cval = glicko_params[i, ]$cval,
        accuracy = mean(ufc_data_loop$glicko_prediction_accurate, na.rm = TRUE))
}

close(pb)
stopCluster(cluster)

as.data.frame(glicko_performance)
```
rd = 290, cval = 5 best performance- 54.2%

## Best Glicko
```{r}
ufc_data_glicko_best <- ufc_data[, c(1:7)]
status_df <- NULL
glicko_rating <- NULL
ufc_data_glicko_best$R_glicko_pred_win_prob <- NA
ufc_data_glicko_best$B_glicko_pred_win_prob <- NA


for(j in 1:nrow(ufc_data_glicko_best)){
    #fight
    fight <- ufc_data_glicko_best[j, c("date", "R_fighter", "B_fighter", "R_win")]
    fight$date <- as.numeric(fight$date)
    
    #rating prediction
    if(!is.null(glicko_rating)){
      ufc_data_glicko_best[j, ]$R_glicko_pred_win_prob <- predict(glicko_rating, fight[, -4], tng = 1, trat = c(1500, 290))
      ufc_data_glicko_best[j, ]$B_glicko_pred_win_prob <- predict(glicko_rating, fight[, c(1,3,2)], tng = 1, trat = c(1500, 290))
    }
    
    #rating generation
    gl <- glicko(fight, status = status_df, init = c(1500, 290), cval = 5)
    
    #glicko_rating for future predictions
    glicko_rating <- gl
    
    #status for future input
    status_df <- gl$ratings
  }
  
#Glicko Performance
ufc_data_glicko_best$glicko_predict_winner <- NA
ufc_data_glicko_best$glicko_predict_winner[ufc_data_glicko_best$R_glicko_pred_win_prob > ufc_data_glicko_best$B_glicko_pred_win_prob] <-  "Red"
ufc_data_glicko_best$glicko_predict_winner[ufc_data_glicko_best$R_glicko_pred_win_prob < ufc_data_glicko_best$B_glicko_pred_win_prob] <- "Blue"
ufc_data_glicko_best$glicko_predict_winner[ufc_data_glicko_best$R_glicko_pred_win_prob == ufc_data_glicko_best$B_glicko_pred_win_prob] <- "Draw"
ufc_data_glicko_best$glicko_prediction_accurate <- NA
ufc_data_glicko_best$glicko_prediction_accurate[ufc_data_glicko_best$glicko_predict_winner == ufc_data_glicko_best$Winner] <- 1
ufc_data_glicko_best$glicko_prediction_accurate[ufc_data_glicko_best$glicko_predict_winner != ufc_data_glicko_best$Winner] <- 0

View(ufc_data_glicko_best)
```

## Prediction Accuracy w/ Win Probability Difference
```{r}
glicko_performance_win_diff <- data.frame()
win_diffs <- seq(0, 1, .05)
for(win_diff in win_diffs){
  loop_row <- cbind(win_diff, 
                    nrow(ufc_data_glicko_best[abs(ufc_data_glicko_best$R_glicko_pred_win_prob - ufc_data_glicko_best$B_glicko_pred_win_prob) >= win_diff, ]), 
                    mean(ufc_data_glicko_best[abs(ufc_data_glicko_best$R_glicko_pred_win_prob - ufc_data_glicko_best$B_glicko_pred_win_prob) >= win_diff, "glicko_prediction_accurate"], na.rm = TRUE))
  
  glicko_performance_win_diff <- rbind(glicko_performance_win_diff, loop_row)
}
colnames(glicko_performance_win_diff) <- c(">= Abs(Win Probabilty Difference)", "Number of Fights", "Prediction Accuracy") 
glicko_performance_win_diff
```


```{python}
from whr import whole_history_rating
import pandas as pd
import numpy as np

ufc_data_py = pd.DataFrame(r.ufc_data)
ufc_data_py = ufc_data_py[["R_fighter", "B_fighter", "Winner", "date_numeric"]]
#drop draws
ufc_data_py = ufc_data_py[ufc_data_py["Winner"] != "Draw"]
ufc_data_py["Winner_WHR"] = np.where(ufc_data_py["Winner"] == "Red", "B", "W")

whr = whole_history_rating.Base({'w2':14})

for index, fight in ufc_data_py.iterrows():
  whr.create_game(fight["R_fighter"], fight["B_fighter"], fight["Winner_WHR"], fight["date_numeric"], 0)

whr.auto_iterate(time_limit = 10 precision = 10E-3)


```

